services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    # O volume geral foi removido para garantir a estabilidade do ambiente do contentor.
    # As alterações no código exigirão uma nova construção da imagem.
    env_file:
      - .env

  generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./output:/app/output
      - ./templates:/app/templates
