services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes: # <-- ADICIONE ESTA LINHA
      - .:/app # <-- E ESTA LINHA
    env_file:
      - .env

  generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./output:/app/output
      - ./templates:/app/templates
